config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :quotes do
    resources :line_item_dates, except: [:index, :show] do
      resources :line_items, except: [:index, :show]
    end
  end

  root to: "pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :users, dependent: :destroy
  has_many :quotes, dependent: :destroy

  validates :name, presence: true
end

app/models/line_item.rb
class LineItem < ApplicationRecord
  belongs_to :line_item_date
  
  validates :name, presence: true
  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validates :unit_price, presence: true, numericality: { greater_than: 0 }

  delegate :quote, to: :line_item_date

  def total_price
    quantity * unit_price
  end
end

app/models/line_item_date.rb
class LineItemDate < ApplicationRecord
  belongs_to :quote
    has_many :line_items, dependent: :destroy
  
    validates :date, presence: true, uniqueness: { scope: :quote_id }
    scope :ordered, -> { order(date: :asc) }
end


# class LineItem < ApplicationRecord
#   belongs_to :line_item_date

#   validates :name, presence: true
#   validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
#   validates :unit_price, presence: true, numericality: { greater_than: 0 }

#   delegate :quote, to: :line_item_date

#   def total_price
#     quantity * unit_price
#   end
# end

app/models/quote.rb
class Quote < ApplicationRecord
  belongs_to :company
  has_many :line_item_dates, dependent: :destroy
  has_many :line_items, through: :line_item_dates

  validates :name, presence: true

  scope :ordered, -> { order(id: :desc) }

  broadcasts_to -> (quote) {[quote.company, "quotes"]}, inserts_by: :prepend

  def total_price
    line_items.sum(&:total_price)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,:validatable
        #  :recoverable, :rememberable, 

  belongs_to :company

  def name
    email.split("@").first.capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!, unless: :devise_controller?
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys:[:company_id])
  end

  private

  def current_company
    @current_company ||= current_user.company if user_signed_in?
  end

  helper_method :current_company
end

app/controllers/line_item_dates_controller.rb
class LineItemDatesController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date, only: [:edit, :update, :destroy]

  def new
    @line_item_date = @quote.line_item_dates.build
  end

  def create
    @line_item_date = @quote.line_item_dates.build(line_item_date_params)
    respond_to do |format|
      if @line_item_date.save
        format.turbo_stream {flash.now[:notice] = "Date was successfully added."}
        format.html { redirect_to quote_path(@quote), notice: "Date was successfully added." }
      else
        format.html {render :new, status: unprocessable_entity}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @line_item_date.update(line_item_date_params)
        format.turbo_stream {flash.now[:notice] = "Date was successfully updated."}
        format.html { redirect_to quote_path(@quote), notice: "Date was successfully updated." }
      else
        format.html{ render :edit, status: unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      @line_item_date.destroy
      format.turbo_stream{ flash.now[:notice] = "Date was successfully deleted."}
      format.html{ redirect_to quote_path(@quote), notice: "Date was successfully destroyed." }
    end
  end

  private

  def line_item_date_params
    params.require(:line_item_date).permit(:date)
  end

  def set_quote
    @quote = current_company.quotes.find(params[:quote_id])
  end

  def set_line_item_date
    @line_item_date = @quote.line_item_dates.find(params[:id])
  end
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_quote
  before_action :set_line_item_date
  before_action :set_line_item, only: [:edit, :update, :destroy]

  def new
    @line_item = LineItem.new
  end

  def create
    @line_item = @line_item_date.line_items.build(line_items_params)
    if @line_item.save
      respond_to do |format|
        format.turbo_stream{ flash.now[:notice] = "Item was successfully saved"}
        format.html{ redirect_to quote_path(@quote), notice: "Item was successfully saved" }
      end
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @line_item.update(line_items_params)
      respond_to do |format|
        format.html{ redirect_to quote_path(@quote), notice: "Item was successfully updated" }
        format.turbo_stream{flash.now[:notice]= "Item was successfully updated"}
      end
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    respond_to do |format|
      if @line_item.destroy
        format.html{redirect_to quote_path(@quote), notice: "Item has been successfully destroyed"}
        format.turbo_stream{flash.now[:notice] = "Item was successfully destroyed"}
      end
    end
  end

  private

  def line_items_params
    params.require(:line_item).permit(:name, :description, :quantity, :unit_price, :line_item_date_id)
  end

  def set_quote
    @quote = Quote.find(params[:quote_id])
  end

  def set_line_item
    @line_item = LineItem.find(params[:id])
  end

  def set_line_item_date
    @line_item_date = LineItemDate.find(params[:line_item_date_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy]
  def index
    @quotes = current_company.quotes.all
  end

  def show
    @line_item_dates = @quote.line_item_dates.includes(:line_items).ordered
  end

  def new
    @quote = Quote.new
  end

  def create
    @quote = current_company.quotes.build(quote_params)
    respond_to do |format|
      if @quote.save
        format.html { redirect_to quotes_path, notice: "Quote was successfully created." }
        format.turbo_stream {flash.now[:notice] = "Quote was successfully created." }
      else
        format.html{ render :new, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end 

  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html {redirect_to quotes_path, notice: "Quote was successfully updated."}
        format.turbo_stream { flash.now[:notice] = "Quote was successfully updated."}
      else
        format.turbo_stream { render :edit, status: :unprocessable_entity }  
      end
    end
  end

  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_path, notice: "Quote was successfully destroyed." }
      format.turbo_stream { flash.now[:notice] = "Quote was successfully destroyed."}
    end
  end

  private

  def set_quote
    @quote = current_company.quotes.find(params[:id])
  end
  
  def quote_params
    params.require(:quote).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def form_error_notification(object)
    if object.errors.any?
      tag.div class: "error-message" do
        object.errors.full_messages.to_sentence.capitalize
      end
    end
  end
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="flash__message" data-controller="removals"
    data-action="animationend->removals#remove">
    <%= message %>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<header >
  <nav class="navbar">
    <% if user_signed_in? %>
      <div class="navbar__brand">
        <%= link_to current_company.name, quotes_path %>
      </div>
      <div class="navbar__name">
        <%= current_user.name%>
      </div>
      <%= button_to "Sign out", destroy_user_session_path, method: :delete,
              class: "btn btn-dark" %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark navbar__right" %>
    <% end %>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuoteEditor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render "layouts/navbar" %>
    <main class="container">
      <div id="flash" class="flash">
        <%= render "layouts/flash" %>
      </div>
      <%= yield %>
    <main>
  </body>
</html>

app/views/line_item_dates/_form.html.erb
<%= simple_form_for [quote, line_item_date], html: { class: "form line-item-date"} do |f| %>
  <% if line_item_date.errors.any? %>
    <div class="error-message">
      <%= form_error_notification(line_item_date)%>
    </div>
  <% end %>

  <%= f.input :date, html5: true, input_html: { autofocus: true } %>
  <%= link_to "Cancel", quote_path(quote), class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/line_item_dates/_line_item_date.html.erb
<%= turbo_frame_tag line_item_date do%>
  <div class="line-item-date">
    <%= turbo_frame_tag dom_id(line_item_date, :edit) do %>

      <div class="line-item-date__header">
        <h2 class="line-item-date__title">
          <%= l(line_item_date.date, format: :long) %>  
        </h2>

        <div class="line-item-date__actions">
          <%= button_to "Delete", 
                        [quote, line_item_date],
                        method: :delete,
                        form: { date: { turbo_confirm: "Are you sure?" } },
                        class: "btn btn--light" %>
          <%= link_to "Edit", 
                    [:edit, quote, line_item_date],
                    class: "btn btn--light" %>
        </div>
      </div>
    <% end %>
    <div class="line-item-date__body">
      <div class="line-item line-item--header">
        <div class="line-item__name">Article</div>
        <div class="line-item__quantity">Quantity</div>
        <div class="line-item__price">Price</div>
        <div class="line-item__actions"></div>
      </div>

      <%= turbo_frame_tag "line_items" do%>
        <%= render line_item_date.line_items, quote: quote, line_item_date: line_item_date %>
      <% end %>

      <%= turbo_frame_tag dom_id(LineItem.new, dom_id(line_item_date)) %>
      
      <div class="line-item-date__footer">
        <%= link_to "Add item", [:new, quote, line_item_date, :line_item], data: {turbo_frame: dom_id(LineItem.new, dom_id(line_item_date))}, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
<% end %>

app/views/line_item_dates/create.turbo_stream.erb
<%= turbo_stream.prepend "line_item_dates", partial: "line_item_dates/line_item_date", locals: {quote: @quote, line_item_date: @line_item_date} %>
<%= turbo_stream.update LineItemDate.new, "" %>

<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/line_item_dates/destroy.turbo_stream.erb
<%= turbo_stream.remove @line_item_date %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

<%= turbo_stream.update dom_id(@quote, :total) do %>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/line_item_dates/edit.html.erb
<%= turbo_frame_tag dom_id(@line_item_date, :edit) do%>
  <%= render partial: "form", locals:{ quote: @quote, line_item_date: @line_item_date } %>
<% end %>

app/views/line_item_dates/new.html.erb
<div>
  <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote)%>

  <div>
    <h1>New date</h1>
  </div>
  <%= turbo_frame_tag dom_id(LineItemDate.new) do%>
    <%= render "form", quote: @quote, line_item_date: @line_item_date %>
  <% end %>
</div>

app/views/line_item_dates/update.turbo_stream.erb
<%= turbo_stream.prepend "line_item_dates" do %>
  <%= render @line_item_date, quote: @quote %>
<% end %>

<%= turbo_stream.prepend "flash", partial: "layouts/flash"%>

app/views/line_items/_form.html.erb
<%= simple_form_for [quote, line_item_date, line_item],
                    html: { class: "form line-item line-item--form" } do |f| %>

  <%= form_error_notification(line_item) %>

  <%= f.input :name,
              wrapper_html: { class: "line-item__name" },
              input_html: { autofocus: true, placeholder: :name } %>
  <%= f.input :quantity,
              wrapper_html: { class: "line-item__quantity" }, input_html: {placeholder: :quantity}%>
  <%= f.input :unit_price,
              wrapper_html: { class: "line-item__price" }, input_html: {placeholder: :price} %>
  <%= f.input :description,
              wrapper_html: { class: "line-item__description" }, input_html: {placeholder: :description} %>

  <div class="line-item__actions">
    <%= link_to "Cancel", quote_path(quote), class: "btn btn--light" %>
    <%= f.submit class: "btn btn--secondary" %>
  </div>
<% end %>

app/views/line_items/_line_item.html.erb
<%= turbo_frame_tag dom_id(line_item) do%>
  <div class="line-item">
    <div class="line-item__name">
      <%= line_item.name %>
      <div class="line-item__description">
        <%= simple_format line_item.description %>
      </div>
    </div>
    <div class="line-item__quantity-price">
      <%= line_item.quantity %>
      &times;
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="line-item__price">
      <%= number_to_currency line_item.unit_price %>
    </div>
    <div class="line-item__actions">
      <%= button_to "Delete", 
            [quote, line_item_date, line_item],
            method: :delete,
            class: "btn btn--light" %>
        <%= link_to "Edit", 
          [:edit, quote, line_item_date, line_item],
          class: "btn btn--light"
        %>
    </div>
  </div>
<% end %>

app/views/line_items/create.turbo_stream.erb
<%= turbo_stream.prepend "line_items", partial: "line_items/line_item", 
    locals: {quote: @quote, line_item: @line_item, line_item_date: @line_item_date} %>

<%= turbo_stream.update dom_id(LineItem.new, dom_id(@line_item_date)), "" %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

<%= turbo_stream.update dom_id(@quote, :total) do%>
  <%= render "quotes/total", quote: @quote %>
<% end %>

<%= turbo_stream.update dom_id(@quote, :total_top) do%>
  <%= render "quotes/total_top", quote: @quote %>
<% end %>

app/views/line_items/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@line_item)%>
<%= turbo_stream.prepend "flash", partial: "layouts/flash"%>

<%= turbo_stream.update dom_id(@quote, :total) do%>
  <%= render "quotes/total", quote: @quote %>
<% end %>

<%= turbo_stream.update dom_id(@quote, :total_top) do%>
  <%= render "quotes/total_top", quote: @quote %>
<% end %>

app/views/line_items/edit.html.erb
<%= turbo_frame_tag dom_id(@line_item) do%>
  <%= render partial: "form", locals: {quote: @quote, line_item_date: @line_item_date, line_item: @line_item}%>
<% end %>

app/views/line_items/new.html.erb
  <div>
    <%= link_to sanitize("&larr; Back to quote"), quote_path(@quote) %>

    <div class="header">
      <h1>New item for <%= l(@line_item_date.date, format: :long) %></h1>
    </div>
    <%= turbo_frame_tag dom_id(LineItem.new, dom_id(@line_item_date)) do%>
      <%= render "form",
                quote: @quote,
                line_item_date: @line_item_date,
                line_item: @line_item %>
      <% end %>
  </div>

app/views/line_items/update.turbo_stream.erb
<%= turbo_stream.prepend "line_items", partial: "line_items/line_item", 
locals: {quote: @quote, line_item: @line_item, line_item_date: @line_item_date} %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

<%= turbo_stream.update dom_id(@quote, :total) do%>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/pages/home.html.erb
<section>
  <h1>Request for your orders</h1>
  <% if user_signed_in? %>
    <%= link_to "View quotes", quotes_path, class: "btn btn--dark" %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path, class: "btn btn--dark" %>
  <% end %>
</section>

app/views/quotes/_empty_state.html.erb
<div class="empty-state empty-state--only-child">
  <p class="empty-state__text">
    You don't have any quotes yet!
  </p>

  <%= link_to "Add quote", new_quote_path, data: { turbo_frame: dom_id(Quote.new) },class: "btn btn--primary" %>
</div>

app/views/quotes/_form.html.erb
<%= simple_form_for quote, html: { class: "quote form" } do |f| %>
  <% if quote.errors.any? %>
    <div class="error-message">
      <%= form_error_notification(quote)%>
    </div>
  <% end %>

  <%= f.input :name, input_html: { autofocus: true } %>
  <%= link_to "cancel", quotes_path, class: "btn btn--light" %>
  <%= f.submit class: "btn btn--secondary" %>
<% end %>

app/views/quotes/_quote.html.erb
<%= turbo_frame_tag quote do%>
  <div class="quote">
      <%= link_to quote.name, quote_path(quote), data: { turbo_frame: "_top" }  %>
      <div class="quote__actions">
        <%= button_to "Delete", quote_path(quote), method: :delete, class: "btn btn--light" %>
        <%= link_to "Edit", edit_quote_path(quote), class: "btn btn--light" %>
      </div>
  </div>
<% end %>

app/views/quotes/_total.html.erb
<footer class="quote-total">
  <div class="quote-total__inner container">
    <div>Total:</div>
    <div><%= number_to_currency quote.total_price %></div>
  </div>
</footer>

app/views/quotes/_total_top.html.erb
<div class="quote-total__inner container">
  <div><span>Total:</span><%= number_to_currency quote.total_price %></div>
</div>

app/views/quotes/create.turbo_stream.erb
<%= turbo_stream.prepend "quotes", partial: "quotes/quote", locals: { quote: @quote } %>
<%= turbo_stream.update Quote.new, ""%>
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>

app/views/quotes/destroy.turbo_stream.erb
<%= turbo_stream.remove @quote %>
<%= turbo_stream.prepend "flash", partial: "layouts/flash"%>

app/views/quotes/edit.html.erb
<div>
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>Edit quote</h1>
  </div>
  <%= turbo_frame_tag @quote do%>
    <%= render "form", quote: @quote %>
  <% end %>
</div>

app/views/quotes/index.html.erb
<section>
  <%= turbo_stream_from current_company, "quotes" %>
  <%= turbo_frame_tag "first_turbo_frame" do %>
    <div class="header">
      <h1>Quotes</h1>
      <%= link_to "New quote", new_quote_path, data: { turbo_frame: dom_id(Quote.new) }, class: "btn btn--primary" %>
    </div>
  <% end %>
  
  <%= turbo_frame_tag Quote.new %>
  
  <%= turbo_frame_tag "quotes" do%>
    <%= render "quotes/empty_state"%>
    <%= render @quotes %>
  <% end %>
</section>

app/views/quotes/new.html.erb
<section class="container">
  <%= link_to sanitize("&larr; Back to quote"), quotes_path %>
  <div class="header">
    <h1>New quote</h1>
  </div>
  <%= turbo_frame_tag @quote do%>
    <%= render "form", quote: @quote %>
  <% end %>
</section>

app/views/quotes/show.html.erb
<%= turbo_stream_from "line_item_dates"%>
<div>
  <%= link_to sanitize("&larr; Back to quotes"), quotes_path %>
  <div class="header">
    <h1>
      <%= @quote.name %>
    </h1>
    <%= turbo_frame_tag dom_id(@quote, :total_top) do%>
        <%= render "quotes/total_top", quote: @quote %>
    <% end %>
  </div>

  <%= link_to "New date", new_quote_line_item_date_path(@quote), 
        data: {turbo_frame: dom_id(LineItemDate.new)}, 
        class: "btn btn--primary" %>

  <%= turbo_frame_tag LineItemDate.new %>

  <%= turbo_frame_tag "line_item_dates" do%>
    <%= render @line_item_dates, quote: @quote %>
  <% end %>
</div>
<%= turbo_frame_tag dom_id(@quote, :total) do%>
  <%= render "quotes/total", quote: @quote %>
<% end %>

app/views/quotes/update.turbo_stream.erb
<%= turbo_stream.prepend "flash", partial: "layouts/flash" %>